<?php

$page=(isset($_GET['page']))?$_GET['page']:0;
if(isset($_GET['site'])){
	if($_GET['site']=='panda'){
		if(isset($_GET['roomid'])){
			//$json=file_get_contents('http://www.panda.tv/api_room?roomid='.$_GET['roomid']);
			$json=json_decode(file_get_contents('http://www.panda.tv/api_room_v2?roomid='.$_GET['roomid']),true);
			$line=explode('_',$json['data']['videoinfo']['plflag']);
			$array['m3u8']='http://pl-hls'.$line[1].'.live.panda.tv/live_panda/'.$json['data']['videoinfo']['room_key'].'.m3u8';
			$array['name']=$json['data']['hostinfo']['name'];
			$array['title']=$json['data']['roominfo']['name'];
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://static.api.m.panda.tv/android_hd/alllist_.json?pageno='.($page+1)),true);
			}else{
				$json=json_decode(file_get_contents('http://static.api.m.panda.tv/android_hd/catelist_.json?cate='.$_GET['cate'].'&pageno='.($page+1)),true);
			}
			for($i=0;$i<count($json['data']['items']);$i++){
				$array[$i]['roomid']=$json['data']['items'][$i]['id'];
				$array[$i]['title']=$json['data']['items'][$i]['name'];
				$array[$i]['thumb']=$json['data']['items'][$i]['pictures']['img'];
				$array[$i]['nickName']=$json['data']['items'][$i]['userinfo']['nickName'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode(file_get_contents('http://static.api.m.panda.tv/android_hd/cate.json'),true);
			count($json['data']);
			for($i=0;$i<count($json['data']);$i++){
				$array[$i]['cate']=$json['data'][$i]['ename'];
				$array[$i]['name']=$json['data'][$i]['cname'];
			}
		}
	}elseif($_GET['site']=='douyu'){
		if(isset($_GET['roomid'])){
			$json=json_decode(file_get_contents('http://m.douyu.com/html5/live?roomId='.$_GET['roomid']),true);
			$array['m3u8']=$json['data']['hls_url'];
			$array['name']=$json['data']['nickname'];
			$array['title']=$json['data']['room_name'];
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://capi.douyucdn.cn/api/v1/live?limit=20&offset='.($page*20)),true);
			}else{
				$json=json_decode(file_get_contents('http://capi.douyucdn.cn/api/v1/live/'.$_GET['cate'].'?limit=20&offset='.($page*20)),true);
			}
			for($i=0;$i<count($json['data']);$i++){
				$array[$i]['roomid']=$json['data'][$i]['room_id'];
				$array[$i]['title']=$json['data'][$i]['room_name'];
				$array[$i]['thumb']=$json['data'][$i]['room_src'];
				$array[$i]['nickName']=$json['data'][$i]['nickname'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode(file_get_contents('http://capi.douyucdn.cn/api/v1/getColumnDetail'),true);
			for($i=0;$i<count($json['data']);$i++){
				$array[$i]['cate']=$json['data'][$i]['tag_id'];
				$array[$i]['name']=$json['data'][$i]['tag_name'];
			}
		}
	}elseif($_GET['site']=='zhanqi'){
		if(isset($_GET['roomid'])){
			$json=json_decode(file_get_contents('http://www.zhanqi.tv/api/static/live.domain/'.$_GET['roomid'].'.json'),true);
			$array['m3u8']='http://dlhls.cdn.zhanqi.tv/zqlive/'.$json['data']['videoId'].'.m3u8';
			$array['name']=$json['data']['nickname'];
			$array['title']=$json['data']['title'];
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://www.zhanqi.tv/api/static/live.hots/20-'.($page+1).'.json'),true);
			}else{
				$json=json_decode(file_get_contents('http://www.zhanqi.tv/api/static/game.lives/'.$_GET['cate'].'/20-'.($page+1).'.json'),true);
			}
			for($i=0;$i<count($json['data']['rooms']);$i++){
				$array[$i]['roomid']=$json['data']['rooms'][$i]['code'];
				$array[$i]['title']=$json['data']['rooms'][$i]['title'];
				$array[$i]['thumb']=$json['data']['rooms'][$i]['spic'];
				$array[$i]['nickName']=$json['data']['rooms'][$i]['nickname'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode(file_get_contents('http://www.zhanqi.tv/api/static/game.lists/100-1.json'),true);
			for($i=0;$i<count($json['data']['games']);$i++){
				$array[$i]['cate']=$json['data']['games'][$i]['id'];
				$array[$i]['name']=$json['data']['games'][$i]['name'];
			}
		}
	}elseif($_GET['site']=='quanmin'){
		if(isset($_GET['roomid'])){
			$json=json_decode(file_get_contents('http://www.quanmin.tv/json/rooms/'.$_GET['roomid'].'/info4.json'),true);
			$array['m3u8']=$json['live']['ws']['hls'][0]['src'];
			$array['name']=$json['slug'];
			$array['title']=$json['title'];
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://www.quanmin.tv/json/play/list_'.($page+1).'.json'),true);
			}else{
				$json=json_decode(file_get_contents('http://www.quanmin.tv/json/categories/'.$_GET['cate'].'/list_'.($page+1).'.json'),true);
			}
			for($i=0;$i<count($json['data']);$i++){
				$array[$i]['roomid']=$json['data'][$i]['uid'];
				$array[$i]['title']=$json['data'][$i]['title'];
				$array[$i]['thumb']=$json['data'][$i]['thumb'];
				$array[$i]['nickName']=$json['data'][$i]['nick'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode(file_get_contents('http://www.quanmin.tv/json/categories/list.json'),true);
			for($i=0;$i<count($json);$i++){
				$array[$i]['cate']=$json[$i]['slug'];
				$array[$i]['name']=$json[$i]['name'];
			}
		}
	}elseif($_GET['site']=='bilibili'){
		if(isset($_GET['roomid'])){
			$json=json_decode(file_get_contents('http://live.bilibili.com/api/playurl?platform=h5&cid='.$_GET['roomid']),true);
			$array['m3u8']=$json['data'];
			$json=json_decode(file_get_contents('http://live.bilibili.com/live/getInfo?roomid='.$_GET['roomid']),true);
			$array['name']=$json['data']['ANCHOR_NICK_NAME'];
			$array['title']=$json['data']['ROOMTITLE'];
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://live.bilibili.com/h5/all?ajax=1&page='.($page+1)),true);
			}else{
				$json=json_decode(file_get_contents('http://live.bilibili.com/h5/'.$_GET['cate'].'?ajax=1&page='.($page+1)),true);
			}
			for($i=0;$i<count($json['data']);$i++){
				$array[$i]['roomid']=$json['data'][$i]['roomid'];
				$array[$i]['title']=$json['data'][$i]['title'];
				$array[$i]['thumb']=$json['data'][$i]['cover'];
				$array[$i]['nickName']=$json['data'][$i]['uname'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode('[["mobile","手机直播"],["sing-dance","唱见舞见"],["ent-life","生活娱乐"],["draw","绘画专区"],["otaku","御宅文化"],["single","单机联机"],["online","网络游戏"],["e-sports","电子竞技"],["mobile-game","手游直播"]]',true);
			for($i=0;$i<count($json);$i++){
				$array[$i]['cate']=$json[$i][0];
				$array[$i]['name']=$json[$i][1];
			}
		}
	}elseif($_GET['site']=='huomao'){
		if(isset($_GET['roomid'])){
			$data=file_get_contents('http://www.huomao.com/mobile/mob_live?cid='.$_GET['roomid']);
			preg_match('/id=\"html_stream\" value=\"(.*?)\">/',$data,$m3u8);
			preg_match('/<title>(.*?)_火猫TV_年轻人的直播社区/',$data,$title);
			preg_match('/id=\"html_stream\" value=\"(.*?)\">/',$data,$m3u8);
			$array['m3u8']='http://live-ws.huomaotv.cn/live/'.$m3u8[1].'/playlist.m3u8';
			$array['name']=$json['slug'];
			$array['title']=$title[1];
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://www.huomao.com/mobile/mobChannel_ajax?page='.$page),true);
			}else{
				$json=json_decode(file_get_contents('http://www.huomao.com/mobile/mobChannel_ajax?page='.$page.'&gid='.$_GET['cate']),true);
			}
			for($i=0;$i<count($json['data']['channelList']);$i++){
				$array[$i]['roomid']=$json['data']['channelList'][$i]['id'];
				$array[$i]['title']=$json['data']['channelList'][$i]['channel'];
				$array[$i]['thumb']=$json['data']['channelList'][$i]['image'];
				$array[$i]['nickName']=$json['data']['channelList'][$i]['nickname'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode(file_get_contents('http://www.huomao.com/game/games.json'),true);
			for($i=0;$i<count($json['data']['gamesList']);$i++){
				$array[$i]['cate']=$json['data']['gamesList'][$i]['gid'];
				$array[$i]['name']=$json['data']['gamesList'][$i]['cname'];
			}
		}
	}elseif($_GET['site']=='longzhu'){
		if(isset($_GET['roomid'])){
			$json=json_decode(file_get_contents('http://roomapicdn.plu.cn/room/roomstatus?roomid='.$_GET['roomid']),true);
			$array['title']=$json['Broadcast']['Title'];
			$json=json_decode(file_get_contents('http://livestream.plu.cn/live/getlivePlayurl?roomId='.$_GET['roomid']),true);
			foreach($json['playLines'][0]['urls'] as $row){
				if($row['ext']=='m3u8'){
					$m3u8=$row['securityUrl'];
					break;
				}
			}
			$array['m3u8']=$m3u8;
		}elseif(isset($_GET['cate'])){
			if($_GET['cate']=='all'){
				$json=json_decode(file_get_contents('http://api.plu.cn/tga/streams?max-results=18&start-index='.($page*18).'&sort-by=views'),true);
			}else{
				$json=json_decode(file_get_contents('http://api.plu.cn/tga/streams?max-results=18&start-index='.($page*18).'&sort-by=views&game='.$_GET['cate']),true);
			}
			for($i=0;$i<count($json['data']['items']);$i++){
				$array[$i]['roomid']=$json['data']['items'][$i]['channel']['id'];
				$array[$i]['title']=$json['data']['items'][$i]['channel']['status'];
				$array[$i]['thumb']=$json['data']['items'][$i]['preview'];
				$array[$i]['nickName']=$json['data']['items'][$i]['channel']['name'];
			}
		}elseif(isset($_GET['getcate'])){
			$json=json_decode('[{"id":"4","name":"\u82f1\u96c4\u8054\u76df"},{"id":"5","name":"\u5730\u4e0b\u57ce\u4e0e\u52c7\u58eb"},{"id":"6","name":"\u661f\u9645\u4e89\u9738"},{"id":"7","name":"\u7a7f\u8d8a\u706b\u7ebf"},{"id":"9","name":"QQ\u98de\u8f66"},{"id":"10","name":"QQ\u70ab\u821e"},{"id":"14","name":"\u9006\u6218"},{"id":"15","name":"\u5251\u7075"},{"id":"16","name":"\u67aa\u795e\u7eaa"},{"id":"18","name":"\u82f1\u96c4\u6740"},{"id":"19","name":"NBA2KOL"},{"id":"29","name":"\u7089\u77f3\u4f20\u8bf4"},{"id":"32","name":"\u795e\u4e4b\u6d69\u52ab"},{"id":"33","name":"FIFA Online3"},{"id":"37","name":"\u8857\u5934\u7bee\u7403"},{"id":"38","name":"\u5929\u5929\u9177\u8dd1"},{"id":"41","name":"\u5168\u6c11\u98de\u673a\u5927\u6218"},{"id":"43","name":"\u602a\u7269\u730e\u4ebaOL"},{"id":"45","name":"\u4f7f\u547d\u53ec\u5524OL"},{"id":"46","name":"\u75be\u98ce\u4e4b\u5203"},{"id":"48","name":"\u683c\u6597\u6e38\u620f"},{"id":"49","name":"\u5929\u6daf\u660e\u6708\u5200"},{"id":"54","name":"\u9b54\u517d\u4e89\u97383"},{"id":"55","name":"\u9b54\u517d\u4e16\u754c"},{"id":"58","name":"\u82f1\u9b42\u4e4b\u5203"},{"id":"59","name":"\u96f7\u9706\u6218\u673a"},{"id":"61","name":"\u5929\u5929\u70ab\u6597"},{"id":"64","name":"\u70ed\u8840\u4f20\u5947"},{"id":"97","name":"\u6211\u7684\u4e16\u754c"},{"id":"100","name":"\u8dd1\u8dd1\u5361\u4e01\u8f66"},{"id":"103","name":"\u738b\u8005\u8363\u8000"},{"id":"106","name":"\u5168\u6c11\u8d85\u795e"},{"id":"110","name":"\u5251\u7f513"},{"id":"113","name":"\u5b88\u671b\u5148\u950b"},{"id":"115","name":"\u67aa\u6797\u5f39\u96e8"},{"id":"117","name":"\u6b22\u4e50\u6597\u5730\u4e3b"},{"id":"120","name":"\u7a7f\u8d8a\u706b\u7ebf\u624b\u6e38"},{"id":"131","name":"\u706b\u5f71\u5fcd\u8005"},{"id":"134","name":"\u541b\u4e34\u5929\u4e0b"},{"id":"136","name":"\u9965\u8352"},{"id":"146","name":"\u90e8\u843d\u51b2\u7a81\u7687\u5ba4\u6218\u4e89"},{"id":"179","name":"\u5192\u9669\u5c9b2"},{"id":"187","name":"CSGO"},{"id":"194","name":"\u8d2a\u5a6a\u6d1e\u7a9f"},{"id":"222","name":"\u9f99\u73e0\u6fc0\u6597"},{"id":"224","name":"\u5fa1\u9f99\u5728\u5929\u624b\u673a\u7248"}]',true);
			for($i=0;$i<count($json);$i++){
				$array[$i]['cate']=$json[$i]['id'];
				$array[$i]['name']=$json[$i]['name'];
			}
		}
	}
}
echo json_encode($array);